#username_id=input-email
#password_id=input-password
#login_btn_xpath=//input[@value='Login']


#username=id:input-email
#password=id:input-password
#loginbutton=xpath://input[@value='Login']
#dashboard=xpath://h2[text()='My Account']

username=id:input-email
password=id:input-password
loginbutton=xpath://input[@value='Login']
warning_msg=css:.alert.alert-danger